// <auto-generated />
using System;
using BoundfoxStudios.Smudgy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoundfoxStudios.Smudgy.Data.Migrations
{
    [DbContext(typeof(SmudgyContext))]
    [Migration("20210310203343_AddSessionAndPlayerColumns")]
    partial class AddSessionAndPlayerColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BoundfoxStudios.Smudgy.Data.Entities.Player", b =>
                {
                    b.Property<int>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SocketId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId");

                    b.HasIndex("SocketId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BoundfoxStudios.Smudgy.Data.Entities.Session", b =>
                {
                    b.Property<int>("ClusterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Language")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundTimeInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundsToPlay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClusterId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("HostPlayerId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("BoundfoxStudios.Smudgy.Data.Entities.Session", b =>
                {
                    b.HasOne("BoundfoxStudios.Smudgy.Data.Entities.Player", "HostPlayer")
                        .WithMany("Sessions")
                        .HasForeignKey("HostPlayerId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HostPlayer");
                });

            modelBuilder.Entity("BoundfoxStudios.Smudgy.Data.Entities.Player", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
