name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x 
    - name: Heroku Login
      env: 
        HEROKU_USER_NAME: "${{ secrets.HEROKU_USER_NAME }}"
      run: bash -c 'echo ${{ secrets.HEROKI_API_TOKEN }} | docker login -u $HEROKU_USER_NAME --password-stdin registry.heroku.com'
    - name: Build API
      run: docker build . --tag boundfoxstudios/smudgy-api:$GITHUB_RUN_NUMBER
      working-directory: backend
    - name: Build Web
      run: |
        npm run ci:shared
        docker build . --tag boundfoxstudios/smudgy-web:$GITHUB_RUN_NUMBER
      working-directory: frontend
    - name: Push images
      run: |
        docker tag boundfoxstudios/smudgy-api:$GITHUB_RUN_NUMBER registry.heroku.com/smudgy-api/web:$GITHUB_RUN_NUMBER
        docker tag boundfoxstudios/smudgy-web:$GITHUB_RUN_NUMBER registry.heroku.com/smudgy-web/web:$GITHUB_RUN_NUMBER
        docker push registry.heroku.com/smudgy-api/web:$GITHUB_RUN_NUMBER
        docker push registry.heroku.com/smudgy-web/web:$GITHUB_RUN_NUMBER
    - name: Release images
      env:
        HEROKU_API_KEY: "${{ secrets.HEROKU_API_TOKEN }}"
      run: |
        heroku container:login
        heroku container:release -a smudgy-api web
        heroku container:release -a smudgy-web web
