name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u boundfoxstudios --password-stdin
    - name: Build API
      run: docker build . --tag boundfoxstudios/smudgy-api:$GITHUB_RUN_NUMBER
      working-directory: backend
    - name: Build Web
      run: docker build . --tag boundfoxstudios/smudgy-web:$GITHUB_RUN_NUMBER
      working-directory: frontend
    - name: Push images
      run: |
        docker push boundfoxstudios/smudgy-api
        docker push boundfoxstudios/smudgy-web
