name: Frontend Deployment

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Frontend Deployment
    uses: ./.github/workflows/render.yml
    secrets:
      RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
      RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
    with:
      service-id: smudgy-frontend
